### ISSUE TITLE
Cut frame

### ISSUE THREAD

**Issue by sv3** [the-bakery/T-Copter#3]
- Arms
- Plates

**Comment by mkovaxx** [comment]
# Made the top (dorsal) part of the frame.

## Resources
- Tools used: jigsaw, hacksaw, drill (3.5 mm), clamps.
- Time spent: ~4 hours.

## Notes
- Gluing the blueprint onto the wood worked surprisingly well.
- Need crosshairs and indentations on drill holes for centering.

## Results

![8647190041_abfde1d30a_b](https://f.cloud.github.com/assets/481354/378694/b7901858-a554-11e2-9b32-8f91683d41c7.jpg)
![8647190649_b223347e36_b](https://f.cloud.github.com/assets/481354/378703/774f2936-a555-11e2-9bd4-a6b084a0c702.jpg)

**Comment by sv3** [comment]
Done cutting ventral plate, just need to drill and countersink holes.
